monolog:
    handlers:
        info_log:
            type: rotating_file
            path: "%kernel.logs_dir%/info.log"
            level: info
            channels: [ "!deprecation" ]
            formatter: monolog.formatter.line

        error_log:
            type: rotating_file
            path: "%kernel.logs_dir%/error.log"
            level: error
            channels: [ "!deprecation" ]
            formatter: monolog.formatter.line

        warning_log:
            type: rotating_file
            path: "%kernel.logs_dir%/warning.log"
            level: warning
            channels: [ "!deprecation" ]
            formatter: monolog.formatter.line

        debug_log:
            type: rotating_file
            path: "%kernel.logs_dir%/debug.log"
            level: debug
            channels: [ "!deprecation" ]
            formatter: monolog.formatter.line
