security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPERADMIN: ROLE_ADMIN
    enable_authenticator_manager: true
    hide_user_not_found: false #voir erreur précise pour login
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Compte
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            custom_authenticator: App\Security\AppAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                target: home_index
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin/parametres/new, roles: ROLE_SUPERADMIN }
        - { path: ^/admin, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_USER }
