services:
  DIRECTORY:
    image: symfonymick-dev_gd-imagick-pdo_pgsql
    container_name: DIRECTORY
    volumes:
      - .:/app
      - ./var/log/nginx:/var/log/nginx
      - ./var/log/php-fpm:/var/log/php-fpm
      - ./var/log/supervisor:/var/log/supervisor
    restart: always
    ports:
      - NUMPORT:80
###> doctrine/doctrine-bundle ###
  DIRECTORY-db:
    container_name: DIRECTORY-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dbDIRECTORY
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: DIRECTORY
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "dbDIRECTORY", "-U", "DIRECTORY"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data-DIRECTORY:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data-DIRECTORY:
###< doctrine/doctrine-bundle ###
