services:
  base:
    image: symfonymick-dev_gd-imagick-pdo_pgsql
    container_name: base
    volumes:
      - .:/app
      - ./var/log/nginx:/var/log/nginx
      - ./var/log/php-fpm:/var/log/php-fpm
      - ./var/log/supervisor:/var/log/supervisor
    restart: always
    ports:
      - 23407:80
###> doctrine/doctrine-bundle ###
  database:
    container_name: base-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dbbase
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: base
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "dbbase", "-U", "base"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
